### ISSUE TITLE
Question: How do I format parsed error?

### ISSUE THREAD

**Issue by reggi** [AriaMinaei/pretty-error#23]
I create a module called [`evalmd`](https://github.com/reggi/evalmd) that evaluates markdown files. Ideally I'd only want to show the trace of the markdown file. I don't expect this to be a feature of pretty-error, but I'd like to skip stack trace lines by extension. How after I edit a trace could I assemble the error again? I can't seem to overwrite the `parsedError.trace` variable and throw `parsedError`. @AriaMinaei thoughts?

```js
var ParsedError = require('pretty-error/lib/parsed-error')
var _ = require('lodash')
var parsedError = new ParsedError(err)
var newTrace = _.filter(parsedError.trace, function (line) {
  var validExt = ['.md', '.markdown']
  var lineExt = path.extname(line.file)
  var isMarkdown = _.contains(validExt, lineExt)
  return isMarkdown
})
```

I'm I stuck having to stitch all the pieces together by hand? Or does `pretty-error` have a way to do this?

Ideally I could:

1. set the value of properties `parsedError.setTrace(trace)`
2. convert `parsedError` back to a error `parsedError.toError()`

**Comment by reggi** [comment]
I suppose I can use `pretty-error` and [skip via callback](https://github.com/AriaMinaei/pretty-error#skipping-by-callback). But don't know how to have default default style.

**Comment by reggi** [comment]
Trying to create a "default-default" template. Could use help :cake: 

```javascript
var nullStyle = {
  background: 'none',
  display: 'inline',
  color: 'none',
  bullet: 'none',
  marginLeft: 0,
  marginRight: 0,
}

pe.appendStyle({
  'pretty-error': _.defaults({}, nullStyle),
  'pretty-error > header': nullStyle,
  'pretty-error > header > title > kind': nullStyle,
  'pretty-error > header > title > wrapper': nullStyle,
  'pretty-error > header > colon': nullStyle,
  'pretty-error > header > message': nullStyle,
  'pretty-error > trace': nullStyle,
  'pretty-error > trace > item': _.defaults({

  }, nullStyle),
  'pretty-error > trace > item > header': nullStyle,
  'pretty-error > trace > item > header > pointer > file': nullStyle,
  'pretty-error > trace > item > header > pointer > colon': nullStyle,
  'pretty-error > trace > item > header > pointer > line': nullStyle,
  'pretty-error > trace > item > header > what': nullStyle,
  'pretty-error > trace > item > footer': nullStyle,
  'pretty-error > trace > item > footer > addr': nullStyle,
  'pretty-error > trace > item > footer > extra': nullStyle
})
```

**Comment by AriaMinaei** [comment]
Hey @reggi, reading your second and third comment, it looks like you've made progress on your own, so I'm not sure exactly what the question currently is. So could you rehash your question?

**Comment by reggi** [comment]
@AriaMinaei how do I wrap `pretty-error > trace > item > footer > addr` in parens? I need `:before` and `:after` selectors. Are there any other default declarations I can use?

```js
var _ = require('lodash')
var PrettyError = require('pretty-error')
var pe = new PrettyError()

var nullStyle = {
  background: 'none',
  display: 'inline',
  color: 'none',
  bullet: 'none',
  marginLeft: 0,
  marginRight: 0,
  marginBottom: 0,
  marginTop: 0
}

pe.appendStyle({
  'pretty-error': _.defaults({}, nullStyle),
  'pretty-error > header': nullStyle,
  'pretty-error > header > title > kind': nullStyle,
  'pretty-error > header > colon': _.defaults({
    marginRight: 1
  }, nullStyle),
  'pretty-error > header > message': nullStyle,
  'pretty-error > trace': _.defaults({
    display: 'block',
    marginLeft: 4
  }, nullStyle),
  'pretty-error > trace > item': _.defaults({
    display: 'block',
    bullet: '"at "'
  }, nullStyle),
  'pretty-error > trace > item > header': _.defaults({

  }, nullStyle),
  'pretty-error > trace > item > header > pointer > file': _.defaults({
    display: 'none'
  }, nullStyle),
  'pretty-error > trace > item > header > pointer > colon': _.defaults({
    display: 'none'
  }, nullStyle),
  'pretty-error > trace > item > header > pointer > line': _.defaults({
    display: 'none'
  }, nullStyle),
  'pretty-error > trace > item > header > what': _.defaults({

  }, nullStyle),
  'pretty-error > trace > item > footer': _.defaults({
  }, nullStyle),
  'pretty-error > trace > item > footer > addr': _.defaults({
    // bullet: '"("'
  }, nullStyle),
  'pretty-error > trace > item > footer > extra': nullStyle
})

var e = new Error('Some error message')

var renderedError = pe.render(e)
console.log("///// native error")
console.log(e.stack)
console.log("///// pretty error")
console.log(renderedError)
```

Is giving me this:

```js
///// native error
Error: Some error message
    at Object.<anonymous> (/Users/thomas/Desktop/node-reggi/z-multi-line.js:78:9)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:953:3
///// pretty error
Error: Some error message
    at Object.<anonymous>/Users/thomas/Desktop/node-reggi/z-multi-line.js:78:9
    at Module._compilemodule.js:430:26
    at Object.Module._extensions..jsmodule.js:448:10
    at Module.loadmodule.js:355:32
    at Function.Module._loadmodule.js:310:12
    at Function.Module.runMainmodule.js:471:10
    at startupnode.js:117:18
    at node.js:953:3
```
