### ISSUE TITLE
some stack miss when error is thrown in eval()

### ISSUE THREAD

**Issue by xosuperpig** [AriaMinaei/pretty-error#37]
example code:
```
var pe = new (require("pretty-error"));

try {
	eval(`(function fn(){
		throw new Error('some error');
	})()`)
} catch(e) {
	console.log(e.stack);
	console.log(pe.render(e));
}
```

result:
```
Error: hehe
    at fn (eval at <anonymous> (S:\_TEST_\index.js:4:2), <anonymous>:2:9)
    at eval (eval at <anonymous> (S:\_TEST_\index.js:4:2), <anonymous>:3:4)
    at Object.<anonymous> (S:\_TEST_\index.js:4:2)
    at Module._compile (module.js:570:32)


  Error: hehe
  - index.js:4 Object.<anonymous>
    S:/_TEST_/index.js:4:2

  - module.js:570 Module._compile
    module.js:570:32
```

**Comment by xosuperpig** [comment]
https://github.com/AriaMinaei/pretty-error/blob/master/src/ParsedError.coffee#L109
The problem is caused by the RegExp here. It does not match `eval at <anonymous> (S:\_TEST_\index.js:4:2), <anonymous>:2:9`

**Comment by aight8** [comment]
please fix this
